# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89904a25eca1c1c14e0d5c609173e9372cd2cab9206be5dfca9df3954cf6486a664f3814422a9ecb1473d4764489a9e6639c3f0304c95e834058c2f7a5bd3140

test:
  secret_key_base: bc54272c511c70134dc0ebff123ff17455f21779029c6f499c0a0c6727b449fe2fd17d726a5214f2b42348f1e9916a6aa7f55856d60d634538944ba6a4223b1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
